import Header from "@/components/Header";
import Landing from "@/components/Landing";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>RIC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <main className="bg-white min-h-screen">
        <Landing />
      </main>
    </>
  );
}
